### ISSUE TITLE
Newbie: Can't get reactable to work

### ISSUE THREAD

**Issue by eliasericsson** [beizhedenglong/reactablejs#2]
I'm new to React and I can't manage to get reactablejs to work, here is my attempt at implementing the example code:
[https://github.com/eliasericsson/reactable-example](https://github.com/eliasericsson/reactable-example/commit/6881119e676ddfd34e1d0b2c7d791ed4678fe09e)

This is the error I'm getting:
./node_modules/reactablejs/dist/index.mjs
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

I apologize if I've missed something fundamental.

**Comment by beizhedenglong** [comment]
It seems that create react app doesn't support `ECMAScript Modules`. I published a new version(0.1.3) to npm. Upgrade your reactablejs dependency to 0.1.3. Your `App.js` was written by typescript syntax. If you want use reactablejs is Javascript, there is a JS version [example](https://github.com/beizhedenglong/reactablejs/commit/00d53c3e89a28421a27b2ea1acde01f4a162d7a0#diff-c90d23fc26d6eeec89e1d77807b6bbbbL6)

**Comment by eliasericsson** [comment]
I've now updated to 0.1.3 and it works fine! Thank you very much!

I gather from checking out some other React projects that App.js and App.tsx are interchangable, but the syntax varies a little bit? If there any benefit to using one over the other with reactablejs?

**Comment by beizhedenglong** [comment]
yes, their syntax is different, typescript file  just offer some type information. Typescript and Javascript all work fine with reactablejs.
