### ISSUE TITLE
Stale react state

### ISSUE THREAD

**Issue by MarkDGithub** [beizhedenglong/reactablejs#9]
Hi,
I appreciate the work you have done with this project and I would like to ask if I could help you with the library.
One of the issues which I found is that the event handlers use a stale React state.  I know that there is a workaround by using useRef(). However, this gets complicated when using Redux and leads to duplicate data.
I solved this for the events by refactoring the code to React hooks. Meanwhile I also updated the npm dependancies.
You can find my changes here: [npm-updates-and-using-react-hooks](https://github.com/MarkDGithub/reactablejs/tree/npm-updates-and-using-react-hooks)
I could create a pull request.

**Comment by beizhedenglong** [comment]
PR is welcome. BTW, can give an example to demonstrate this problem?

**Comment by MarkDGithub** [comment]
> can give an example to demonstrate this problem?

I recreated and simplified the problem [here](https://codesandbox.io/s/serene-firefly-8fht7?file=/src/App.js) . The stale counter is just a simplification. This is where I update the Redux store in my real application. 
PR: #10

**Comment by beizhedenglong** [comment]
I see. I checked out you branch, it seems has some issues with the drag demo

https://user-images.githubusercontent.com/12963675/146944298-eabe945a-ec29-4ab6-a3e1-1b07c93fff97.mov

**Comment by MarkDGithub** [comment]
> it seems has some issues with the drag demo

I can't reproduce this issue, I'm using respectively the following commands: yarn install, yarn build-storybook, yarn storybook

https://user-images.githubusercontent.com/20031139/146976777-5545b6e7-6897-4ea0-8720-9a87227a74f1.mov

**Comment by MarkDGithub** [comment]
I also tried if the problem occurs after cloning the project again and checking out the new branch (so basically a blank sheet). But the problem still doesn't occur.

**Comment by beizhedenglong** [comment]
I figured it  out. It was caused by one of my chrome extensions.

**Comment by MarkDGithub** [comment]
Thanks for accepting. Will the npm package be updated automatically?

**Comment by beizhedenglong** [comment]
I just published it to npm. try toreinstall the package
